In [1]:
import pandas as pd
import numpy as np

In [2]:
from tensorflow.keras import datasets

In [3]:
datasets

<module 'keras.api.datasets' from 'C:\\Users\\admin\\anaconda3\\Lib\\site-packages\\keras\\api\\datasets\\__init__.py'>

In [6]:
(x_train,y_train),(x_test,y_test)=datasets.mnist.load_data()

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 2s 0us/step


In [7]:
x_train

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [9]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [13]:
width,height=28,28
input_shape=(width,height,1)

In [15]:
x_train=x_train.reshape(x_train.shape[0],height,width,1)
x_test=x_test.reshape(x_test.shape[0],height,width,1)

In [16]:
x_train.shape

(60000, 28, 28, 1)

In [17]:
y_train.shape

(60000,)

In [18]:
from sklearn.model_selection import train_test_split

In [20]:
x_train,x_val,y_train,y_val=train_test_split(x_train,y_train,test_size=0.1)

In [21]:
len(x_train)

54000

In [22]:
len(x_val)

6000

In [24]:
x_train=(x_train-x_train.mean())/x_train.std()
x_val=(x_val-x_val.mean())/x_val.std()
x_test=(x_test-x_test.mean())/x_test.std()

In [29]:
x_train

array([[[[-0.42405522],
         [-0.42405522],
         [-0.42405522],
         ...,
         [-0.42405522],
         [-0.42405522],
         [-0.42405522]],

        [[-0.42405522],
         [-0.42405522],
         [-0.42405522],
         ...,
         [-0.42405522],
         [-0.42405522],
         [-0.42405522]],

        [[-0.42405522],
         [-0.42405522],
         [-0.42405522],
         ...,
         [-0.42405522],
         [-0.42405522],
         [-0.42405522]],

        ...,

        [[-0.42405522],
         [-0.42405522],
         [-0.42405522],
         ...,
         [-0.42405522],
         [-0.42405522],
         [-0.42405522]],

        [[-0.42405522],
         [-0.42405522],
         [-0.42405522],
         ...,
         [-0.42405522],
         [-0.42405522],
         [-0.42405522]],

        [[-0.42405522],
         [-0.42405522],
         [-0.42405522],
         ...,
         [-0.42405522],
         [-0.42405522],
         [-0.42405522]]],


       [[[-0.42405522],


In [25]:
from tensorflow import keras

In [27]:
num_labels=10
y_train=keras.utils.to_categorical(y_train)

In [28]:
y_train

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [30]:
y_val=keras.utils.to_categorical(y_val)
y_test=keras.utils.to_categorical(y_test)

# MODELLING

In [35]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout,Flatten,Input,Conv2D,MaxPooling2D,AveragePooling2D

In [38]:
model=Sequential()
model.add(Conv2D(6,kernel_size=(5,5),strides=(1,1),activation='tanh',input_shape=(28,28,1)))
model.add(AveragePooling2D(pool_size=(2,2),strides=(1,1)))
model.add(Conv2D(16,kernel_size=(5,5),strides=(1,1),activation='tanh'))
model.add(AveragePooling2D(pool_size=(2,2),strides=(2,2)))
model.add(Conv2D(120,kernel_size=(5,5),strides=(1,1),activation='tanh'))
model.add(Flatten())
model.add(Dense(84,activation='tanh'))
model.add(Dense(num_labels,activation='softmax'))

In [40]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv2d_4 (Conv2D)                    │ (None, 24, 24, 6)           │             156 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ average_pooling2d_2                  │ (None, 23, 23, 6)           │               0 │
│ (AveragePooling2D)                   │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_5 (Conv2D)                    │ (None, 19, 19, 16)          │           2,416 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ average_pooling2d_3                  │ (None, 9, 9, 16)            │               0 │
│ (AveragePooling2D)                   │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_6 (Conv2D)                    │ (None, 5, 5, 120)           │          48,120 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten_1 (Flatten)                  │ (None, 3000)                │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 84)                  │         252,084 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 10)                  │             850 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 303,626 (1.16 MB)

 Trainable params: 303,626 (1.16 MB)

 Non-trainable params: 0 (0.00 B)

In [41]:
model.compile(loss=keras.losses.categorical_crossentropy,optimizer='adam',metrics=['accuracy'])

In [42]:
history=model.fit(x_train,y_train,batch_size=32,epochs=20,verbose=1,validation_data=(x_val,y_val))

Epoch 1/20
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 40s 21ms/step - accuracy: 0.9046 - loss: 0.3134 - val_accuracy: 0.9728 - val_loss: 0.0957
Epoch 2/20
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 34s 20ms/step - accuracy: 0.9717 - loss: 0.0899 - val_accuracy: 0.9757 - val_loss: 0.0841
Epoch 3/20
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 33s 20ms/step - accuracy: 0.9744 - loss: 0.0841 - val_accuracy: 0.9758 - val_loss: 0.0805
Epoch 4/20
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 34s 20ms/step - accuracy: 0.9803 - loss: 0.0657 - val_accuracy: 0.9817 - val_loss: 0.0597
Epoch 5/20
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 33s 19ms/step - accuracy: 0.9808 - loss: 0.0643 - val_accuracy: 0.9850 - val_loss: 0.0550
Epoch 6/20
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 33s 19ms/step - accuracy: 0.9821 - loss: 0.0572 - val_accuracy: 0.9822 - val_loss: 0.0614
Epoch 7/20
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 34s 20ms/step - accuracy: 0.9838 - loss: 0.0537 - val_accuracy: 0.9827 - val_loss: 0.0553
Epoch 8/20
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 33s 19ms/step - accuracy: 0.9849 -

# FINAL TESTING

In [43]:
score=model.evaluate(x_test,y_test,verbose=1)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9819 - loss: 0.0575


In [44]:
score

[0.046033382415771484, 0.98580002784729]